[package]
name = "rust-chibicc"
version = "0.3.0"
authors = ["smirror"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "^4.3.2"
combine-language  = "3.0.2"
nom = "6"

[build-dependencies]

